name: "Question / Support"
description: "Ask a question about usage, integration, or behavior"
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        For general questions, please also check the docs (EN/RU), FAQ, and Troubleshooting pages.
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Be as specific as possible.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context and what you tried
      description: Include relevant code snippets and what you already checked in the docs.
  - type: textarea
    id: env
    attributes:
      label: Environment (optional)
      description: OS, browser, package version (if relevant).

