name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    name: Quality (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type Declarations
        run: npm run types
      - name: Build
        run: npm run build
      - name: Tests + Coverage
        run: npm run coverage
      - name: E2E tests (Playwright)
        run: npm run test:e2e
      - name: Size Gate (≤ 5 KB gzip)
        run: npm run size
      - name: Upload coverage (artifact)
        if: ${{ matrix.node == '22.x' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
